name:                huffman
version:             0.1.0.0
github:              "githubuser/huffman"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/huffman#readme>

dependencies:
- base >= 4.14.1.0 && < 5
- bytestring
- pipes
- pipes-bytestring >= 2.1.7
- pipes-parse
- transformers
- binary
- containers
- lens-family
- pipes-binary

library:
  source-dirs: src
  dependencies:
    - bimap
    - containers
    - binary
    - transformers
    - bytestring

executables:
  huffman-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - huffman
